apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysql
spec:
  strategy:
      type: Recreate
  selector:
    matchLabels:
      app: mysql
  template:
    metadata:
      labels:
        app: mysql
    spec:
      volumes:
      - name: pv-mysql
        hostPath:
            path: /data/mysql/
      containers:
      - name: mysql
        imagePullPolicy: Never
        image: ft_mysql
        ports:
        - containerPort: 3306
        volumeMounts:
         - name: pv-mysql
           mountPath: "./data"
---
apiVersion: v1
kind: Service
metadata:
  name: mysql-service
  annotations:
    metallb.universe.tf/allow-shared-ip: "shared key"
spec:
  type: ClusterIP
  clusterIP: 10.96.83.102
  selector:
    app: mysql
  ports:
    - protocol: TCP
      port: 3306
      targetPort: 3306
