apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysql
spec:
  strategy:
      type: Recreate
  selector:
    matchLabels:
      app: mysql
  template:
    metadata:
      labels:
        app: mysql
    spec:
      volumes:
      - name: pv-mysql
        hostPath:
            path: /data/mysql/
      containers:
      - name: mysql
        imagePullPolicy: Never
        image: my_mysql
        volumeMounts:
         - name: pv-mysql
           mountPath: "./data"
---
apiVersion: v1
kind: Service
metadata:
  name: mysql-service
spec:
  type: ClusterIP
  selector:
    app: mysql
  ports:
    - protocol: TCP
      port: 3306
      name: mysql