apiVersion: apps/v1
kind: Deployment
metadata:
  name: grafana
spec:
  strategy:
      type: Recreate
  selector:
    matchLabels:
      app: grafana
  template:
    metadata:
      labels:
        app: grafana
    spec:
      containers:
      - name: grafana
        imagePullPolicy: Never
        image: ft_grafana
        ports:
        - containerPort: 3000
          name: http
---
apiVersion: v1
kind: Service
metadata:
  name: grafana-service
  annotations:
    metallb.universe.tf/allow-shared-ip: "shared key"
spec:
  type: LoadBalancer
  externalTrafficPolicy: Cluster
  selector:
    app: grafana
  ports:
    - protocol: TCP
      port: 3000
      targetPort: 3000
      nodePort: 3000
      name: http
