apiVersion: apps/v1
kind: Deployment
metadata:
  name: wordpress
spec:
  strategy:
      type: Recreate
  selector:
    matchLabels:
      app: wordpress
  template:
    metadata:
      labels:
        app: wordpress
    spec:
      containers:
      - name: wordpress
        imagePullPolicy: Never
        image: ft_wordpress
        ports:
        - containerPort: 5050
          name: https
---
apiVersion: v1
kind: Service
metadata:
  name: wordpress-service
  annotations:
    metallb.universe.tf/allow-shared-ip: "shared key"
spec:
  type: LoadBalancer
  externalTrafficPolicy: Cluster
  selector:
    app: wordpress
  ports:
    - protocol: TCP
      port: 5050
      targetPort: 5050
      nodePort: 5050
      name: https